### ISSUE TITLE
Issue creating krib-ha cluster

### ISSUE THREAD

**Issue by svallebro** [digitalrebar/provision-content#101]
Hi,

I'm trying to run the krib-live-cluster and I have an issue during the etcd-config task.
It seems to miss the makeroot on the machine.
I am running: 
provision **v3.9.0-tip-4-fd645195a539acebc6e45f8d44bb745677343d8c**
Feature Flags
api-v3, sane-exit-codes, common-blob-size, change-stage-map, job-exit-states, package-repository-handling, profileless-machine, threaded-log-levels, plugin-v2, fsm-runner, plugin-v2-safe-config, workflows, default-workflow, http-range-header, roles, tenants, secure-params, seperate-meta-api, slim-objects

krib content **v1.9.0-tip-15-f7a61da2534f67fc292598e62964b164b3500597**

Here is the log of the task:

Log for Job: 95530bdc-7a1b-4578-af40-50615e105d12
Starting task etcd-config on 59ea578f-c892-4ae6-81b9-7c4d284ecbbd
Starting command ./etcd-config-etcd-config.sh.tmpl

Command running
Configure the etcd cluster
Add initial variables to track members.
Error: Key, etcd/servers, already present on profile k8s
Error: Key, etcd/servers-done, already present on profile k8s
Creating 1 servers
Electing Members to k8s
Error: INVOKE: machines/59ea578f-c892-4ae6-81b9-7c4d284ecbbd: **Action makeroot on machines: Not Found**
Command exited with status 1
Action etcd-config.sh.tmpl finished
Task etcd-config failed
Marked machine 59ea578f-c892-4ae6-81b9-7c4d284ecbbd as not runnable
Updated job 95530bdc-7a1b-4578-af40-50615e105d12 to failed
Task signalled that it failed

Br Simon

**Comment by zehicle** [comment]
@svallebro building the etcd cluster requires the certs plugin right now - if you contact me (@zehicle) on the RackN slack, I can create an org that has access to the certs plugin.

**Comment by galthaus** [comment]
I think this is resolved for now.
