### ISSUE TITLE
krib-dashboard.sh.tmpl - wget: command not found

### ISSUE THREAD

**Issue by graham1228** [digitalrebar/provision-content#109]
As a user of the `krib-install-cluster` workflow I would like the workflow to deploy a fully functional K8s cluster without error's. Currently getting a `wget: command not found` error during the `krib-config `stage, `krib-dashboard` task.

### Logs:
```
./krib-dashboard-krib-dashboard.sh.tmpl@224(): wget -O /tmp/kubernetes-dashboard.yaml https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml
./krib-dashboard-krib-dashboard.sh.tmpl: line 224: wget: command not found
Command exited with status 127
Action krib-dashboard.sh.tmpl finished
Task krib-dashboard failed
Marked machine 9832c35d-ae4c-4945-b4e9-dc1ed9113e6d as not runnable
Updated job 732e297a-eaac-49f6-beb7-851999f94f59 to failed
Task signalled runner to reboot
```

### Proposed Resolution:
I believe we just need to add `wget` to this line
https://github.com/digitalrebar/provision-content/blob/master/krib/templates/krib-dashboard.sh.tmpl#L38

**Comment by sygibson** [comment]
merged
