### ISSUE TITLE
CentOS 6.9 ISO doesn't exists 

### ISSUE THREAD

**Issue by TroubleshooteRJ** [digitalrebar/provision-content#176]
The IsoUrl mentioned in CentOS6.9 bootenv file inside contrib content does not exists anymore.
IsoUrl: "http://mirrors.kernel.org/centos/6.9/isos/x86_64/CentOS-6.9-x86_64-bin-DVD1.iso"

https://github.com/digitalrebar/provision-content/blob/master/contrib/bootenvs/centos-6.9.yml

In fact the ISO can't be found on any official centos mirrors as version starting from 6.0 to 6.9 no longer get any updates, nor any security fix's.

**Comment by galthaus** [comment]
Thanks for updating this.  I've update the centos6 to match.  These are now in tip.
