### ISSUE TITLE
Template config incorrect on Ubuntu when "access-ssh-root-mode" parameter set

### ISSUE THREAD

**Issue by wdennis** [digitalrebar/provision-content#29]
https://github.com/digitalrebar/provision-content/blob/061c3d915e2dfe0f0cd0c77acc3af3af67fbf681/templates/ce-root-remote-access.tmpl#L31 does not succeed in doing the right thing as far as changing the behavior of "PermitRootLogin" on Ubuntu.

The generated post-install.sh file for a Ubuntu OS machine using a Profile that sets the `access-ssh-root-mode` parameter to value "yes" has this line in it:

```echo "PermitRootLogin yes" >> /etc/ssh/sshd_config```

This results in the actual sshd_config file having two active `PermitRootLogin` lines, e.g.:

```
PermitRootLogin without-password
  [...]
PermitRootLogin yes
```
This is undefined, but empirically in my testing, sshd seems to honor only the first of any duplicate stanzas.

The current stock CentOS `sshd_config` has the following lines with `PermitRootLogin` in them:
```[root@centos7box ~]# grep PermitRootLogin /etc/ssh/sshd_config
#PermitRootLogin yes
# the setting of "PermitRootLogin without-password".
```
The current stock Ubuntu `sshd_config` has the following lines with `PermitRootLogin` in them:
```root@testnode01:~# grep PermitRootLogin /etc/ssh/sshd_config
PermitRootLogin prohibit-password
# the setting of "PermitRootLogin without-password".
```

Considering the "yes" value case, this sed command line would end up doing the right thing for either CentOS or Ubuntu:
```sed --in-place -r -e '/^#?PermitRootLogin/ s/^#//' -e '/^#?PermitRootLogin/ s/prohibit-password/yes/' /etc/ssh/sshd_config```

Of course, the value ("yes" in my case) needs to be parameterized to support valid alternate values [without-password|yes|no|forced-commands-only] 

So, replace the "echo .." line in the template with the "sed ..." line with relevant parameterization.

**Comment by galthaus** [comment]
Already fix - along time ago.
